version: '3.3'

services:
  database:
    image: postgres:10.10
    restart: always
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dev_db

  milmove_migrate:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.migrations_local
    links:
      - database
    environment:
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - ENVIRONMENT=test
      - MIGRATION_PATH=file:///migrate/schema;file:///migrate/secure
      - MIGRATION_MANIFEST=/migrate/migrations_manifest.txt
    entrypoint:
      - '/bin/milmove'
      - 'migrate'
    volumes:
      - ./migrations/app/secure:/migrate/secure

  milmove:
    depends_on:
      - database
      - milmove_migrate
    build:
      context: .
      dockerfile: Dockerfile.local
    links:
      - database
    ports:
      - '4000:4000'
    environment:
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - DEVLOCAL_AUTH=true
      - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
      - DOD_CA_PACKAGE=/config/tls/Certificates_PKCS7_v5.6_DoD.der.p7b
      - ENVIRONMENT=test
      - HTTP_ORDERS_SERVER_NAME=orderslocal
      - IWS_RBS_HOST
      - MOVE_MIL_DOD_CA_CERT
      - MOVE_MIL_DOD_TLS_CERT
      - MOVE_MIL_DOD_TLS_KEY
      - MUTUAL_TLS_ENABLED=1
      - TLS_ENABLED=1
      - PGPASSWORD=mysecretpassword
      - SERVE_API_ORDERS=true
    entrypoint:
      - '/bin/milmove'
      - 'serve_orders'
    volumes:
      - ./tmp:/tmp
